[workspace]
members = [
    "pe-0001",
    "pe-0002",
    "pe-0003",
    "pe-0004",
    "pe-0005",
    "pe-0006",
    "pe-0007",
    "pe-0008",
    "pe-0009",
    "pe-0010",
    "pe-0011",
    "pe-0012",
    "pe-0013",
    "pe-0014",
    "pe-0015",
    "pe-0016",
    "pe-0017",
    "pe-0018",
    "pe-0019",
    "pe-0020",
    "pe-0021",
    "pe-0022",
    "pe-0023",
    "pe-0024",
    "pe-0025",
    "pe-0026",
    "pe-0027",
    "pe-0028",
    "pe-0029",
    "pe-0030",
    "pe-0031",
    "pe-0032",
    "pe-0033",
    "pe-0034",
    "pe-0035",
    "pe-0036",
    "pe-0037",
    "pe-0038",
    "pe-0039",
    "pe-0040",
    "pe-0041",
    "pe-0042",
    "pe-0043",
    "pe-0044",
    "pe-0045",
    "pe-0046",
    "pe-0047",
    "pe-0048",
    "pe-0049",
    "pe-0050",
    "pe-0053",
    "pe-0055",
    "pe-0056",
    "pe-0060",
    "pe-0061",
    "pe-0063",
    "pe-0066",
    "pe-0070",
    "pe-0071",
    "pe-0076",
    "pe-0081",
    "pe-0087",
    "pe-0090",
    "pe-0091",
    "pe-0092",
    "pe-0097",
    "pe-0104",
    "pe-0119",
    "pe-0160",
    "pe-0188",
    "pe-0206",
    "pe-0304",
    "pe-0345",
    "pe-0455",
    "pe-0500",
    "pe-0659",
    "pe-0725",
    "pe-0800",
    "pe-0808",
    "pe-0820",
    "pe-0831",
    "pe-0849",
    "pe-0940",
]
resolver = "2"

[workspace.dependencies]
chrono = "0.4.38"
csv = "1.3.0"
itertools = "0.13.0"
num = "0.4.1"
num-bigint = "0.4.6"
num-rational = "0.4"
num-traits = "0.2.19"
primal = "0.3.3"
primes = "0.4.0"
