[workspace]
members = [
    "solutions/pe-0001",
    "solutions/pe-0002",
    "solutions/pe-0003",
    "solutions/pe-0004",
    "solutions/pe-0005",
    "solutions/pe-0006",
    "solutions/pe-0007",
    "solutions/pe-0008",
    "solutions/pe-0009",
    "solutions/pe-0010",
    "solutions/pe-0011",
    "solutions/pe-0012",
    "solutions/pe-0013",
    "solutions/pe-0014",
    "solutions/pe-0015",
    "solutions/pe-0016",
    "solutions/pe-0017",
    "solutions/pe-0018",
    "solutions/pe-0019",
    "solutions/pe-0020",
    "solutions/pe-0021",
    "solutions/pe-0022",
    "solutions/pe-0023",
    "solutions/pe-0024",
    "solutions/pe-0025",
    "solutions/pe-0026",
    "solutions/pe-0027",
    "solutions/pe-0028",
    "solutions/pe-0029",
    "solutions/pe-0030",
    "solutions/pe-0031",
    "solutions/pe-0032",
    "solutions/pe-0033",
    "solutions/pe-0034",
    "solutions/pe-0035",
    "solutions/pe-0036",
    "solutions/pe-0037",
    "solutions/pe-0038",
    "solutions/pe-0039",
    "solutions/pe-0040",
    "solutions/pe-0041",
    "solutions/pe-0042",
    "solutions/pe-0043",
    "solutions/pe-0044",
    "solutions/pe-0045",
    "solutions/pe-0046",
    "solutions/pe-0047",
    "solutions/pe-0048",
    "solutions/pe-0049",
    "solutions/pe-0050",
    "solutions/pe-0053",
    "solutions/pe-0055",
    "solutions/pe-0056",
    "solutions/pe-0060",
    "solutions/pe-0061",
    "solutions/pe-0063",
    "solutions/pe-0066",
    "solutions/pe-0070",
    "solutions/pe-0071",
    "solutions/pe-0076",
    "solutions/pe-0081",
    "solutions/pe-0087",
    "solutions/pe-0090",
    "solutions/pe-0091",
    "solutions/pe-0092",
    "solutions/pe-0097",
    "solutions/pe-0104",
    "solutions/pe-0119",
    "solutions/pe-0160",
    "solutions/pe-0188",
    "solutions/pe-0206",
    "solutions/pe-0304",
    "solutions/pe-0345",
    "solutions/pe-0455",
    "solutions/pe-0500",
    "solutions/pe-0659",
    "solutions/pe-0725",
    "solutions/pe-0800",
    "solutions/pe-0808",
    "solutions/pe-0820",
    "solutions/pe-0831",
    "solutions/pe-0849",
    "solutions/pe-0940",
    "pe-utils",
]
resolver = "2"

[workspace.dependencies]
pe-utils = { path = "pe-utils" }
chrono = "0.4.38"
csv = "1.3.0"
itertools = "0.13.0"
num = "0.4.1"
num-bigint = "0.4.6"
num-rational = "0.4"
num-traits = "0.2.19"
primal = "0.3.3"
primes = "0.4.0"
